# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import front_end_pb2 as front__end__pb2


class FrontStub(object):
    """The catalog component will send invalidate message to the front-end component using Invalidate rpc call
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Invalidate = channel.unary_unary(
                '/unary.Front/Invalidate',
                request_serializer=front__end__pb2.product_front.SerializeToString,
                response_deserializer=front__end__pb2.invalidation_response.FromString,
                )


class FrontServicer(object):
    """The catalog component will send invalidate message to the front-end component using Invalidate rpc call
    """

    def Invalidate(self, request, context):
        """Declare the rpc call "Invalidation" as an unary rpc
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FrontServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Invalidate': grpc.unary_unary_rpc_method_handler(
                    servicer.Invalidate,
                    request_deserializer=front__end__pb2.product_front.FromString,
                    response_serializer=front__end__pb2.invalidation_response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'unary.Front', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Front(object):
    """The catalog component will send invalidate message to the front-end component using Invalidate rpc call
    """

    @staticmethod
    def Invalidate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/unary.Front/Invalidate',
            front__end__pb2.product_front.SerializeToString,
            front__end__pb2.invalidation_response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
