# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: catalog.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rcatalog.proto\x12\x05unary\"\x1f\n\x07product\x12\x14\n\x0cproduct_name\x18\x01 \x01(\t\"1\n\x0equery_response\x12\r\n\x05price\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x05\"/\n\x05order\x12\x14\n\x0cproduct_name\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x05\"$\n\x0corder_result\x12\x14\n\x0corder_result\x18\x01 \x01(\x05\x32i\n\x07\x43\x61talog\x12\x30\n\x05Query\x12\x0e.unary.product\x1a\x15.unary.query_response\"\x00\x12,\n\x05Order\x12\x0c.unary.order\x1a\x13.unary.order_result\"\x00\x62\x06proto3')



_PRODUCT = DESCRIPTOR.message_types_by_name['product']
_QUERY_RESPONSE = DESCRIPTOR.message_types_by_name['query_response']
_ORDER = DESCRIPTOR.message_types_by_name['order']
_ORDER_RESULT = DESCRIPTOR.message_types_by_name['order_result']
product = _reflection.GeneratedProtocolMessageType('product', (_message.Message,), {
  'DESCRIPTOR' : _PRODUCT,
  '__module__' : 'catalog_pb2'
  # @@protoc_insertion_point(class_scope:unary.product)
  })
_sym_db.RegisterMessage(product)

query_response = _reflection.GeneratedProtocolMessageType('query_response', (_message.Message,), {
  'DESCRIPTOR' : _QUERY_RESPONSE,
  '__module__' : 'catalog_pb2'
  # @@protoc_insertion_point(class_scope:unary.query_response)
  })
_sym_db.RegisterMessage(query_response)

order = _reflection.GeneratedProtocolMessageType('order', (_message.Message,), {
  'DESCRIPTOR' : _ORDER,
  '__module__' : 'catalog_pb2'
  # @@protoc_insertion_point(class_scope:unary.order)
  })
_sym_db.RegisterMessage(order)

order_result = _reflection.GeneratedProtocolMessageType('order_result', (_message.Message,), {
  'DESCRIPTOR' : _ORDER_RESULT,
  '__module__' : 'catalog_pb2'
  # @@protoc_insertion_point(class_scope:unary.order_result)
  })
_sym_db.RegisterMessage(order_result)

_CATALOG = DESCRIPTOR.services_by_name['Catalog']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PRODUCT._serialized_start=24
  _PRODUCT._serialized_end=55
  _QUERY_RESPONSE._serialized_start=57
  _QUERY_RESPONSE._serialized_end=106
  _ORDER._serialized_start=108
  _ORDER._serialized_end=155
  _ORDER_RESULT._serialized_start=157
  _ORDER_RESULT._serialized_end=193
  _CATALOG._serialized_start=195
  _CATALOG._serialized_end=300
# @@protoc_insertion_point(module_scope)
