# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import catalog_pb2 as catalog__pb2


class CatalogStub(object):
    """the ToyStore service will have two rpc calls which are "Query" and "Buy"
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Query = channel.unary_unary(
                '/unary.Catalog/Query',
                request_serializer=catalog__pb2.product.SerializeToString,
                response_deserializer=catalog__pb2.query_response.FromString,
                )
        self.Order = channel.unary_unary(
                '/unary.Catalog/Order',
                request_serializer=catalog__pb2.order.SerializeToString,
                response_deserializer=catalog__pb2.order_result.FromString,
                )


class CatalogServicer(object):
    """the ToyStore service will have two rpc calls which are "Query" and "Buy"
    """

    def Query(self, request, context):
        """Declare the rpc call "Query" as an unary rpc
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Order(self, request, context):
        """Declare the rpc call "Buy" as an unary rpc
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CatalogServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Query': grpc.unary_unary_rpc_method_handler(
                    servicer.Query,
                    request_deserializer=catalog__pb2.product.FromString,
                    response_serializer=catalog__pb2.query_response.SerializeToString,
            ),
            'Order': grpc.unary_unary_rpc_method_handler(
                    servicer.Order,
                    request_deserializer=catalog__pb2.order.FromString,
                    response_serializer=catalog__pb2.order_result.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'unary.Catalog', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Catalog(object):
    """the ToyStore service will have two rpc calls which are "Query" and "Buy"
    """

    @staticmethod
    def Query(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/unary.Catalog/Query',
            catalog__pb2.product.SerializeToString,
            catalog__pb2.query_response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Order(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/unary.Catalog/Order',
            catalog__pb2.order.SerializeToString,
            catalog__pb2.order_result.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
