# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import order2_pb2 as order2__pb2


class RecoveryStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RequestMissingLogs = channel.stream_unary(
                '/unary.Recovery/RequestMissingLogs',
                request_serializer=order2__pb2.missing_number.SerializeToString,
                response_deserializer=order2__pb2.ping2.FromString,
                )
        self.BackOnline = channel.unary_unary(
                '/unary.Recovery/BackOnline',
                request_serializer=order2__pb2.ping2.SerializeToString,
                response_deserializer=order2__pb2.ping2.FromString,
                )


class RecoveryServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RequestMissingLogs(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BackOnline(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RecoveryServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RequestMissingLogs': grpc.stream_unary_rpc_method_handler(
                    servicer.RequestMissingLogs,
                    request_deserializer=order2__pb2.missing_number.FromString,
                    response_serializer=order2__pb2.ping2.SerializeToString,
            ),
            'BackOnline': grpc.unary_unary_rpc_method_handler(
                    servicer.BackOnline,
                    request_deserializer=order2__pb2.ping2.FromString,
                    response_serializer=order2__pb2.ping2.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'unary.Recovery', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Recovery(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RequestMissingLogs(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/unary.Recovery/RequestMissingLogs',
            order2__pb2.missing_number.SerializeToString,
            order2__pb2.ping2.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def BackOnline(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/unary.Recovery/BackOnline',
            order2__pb2.ping2.SerializeToString,
            order2__pb2.ping2.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
