# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: order2.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0corder2.proto\x12\x05unary\"<\n\x0emissing_number\x12\x14\n\x0corder_number\x18\x01 \x01(\x05\x12\x14\n\x0c\x63omponent_id\x18\x02 \x01(\x05\"\x1c\n\x05ping2\x12\x13\n\x0bping_number\x18\x01 \x01(\x05\x32u\n\x08Recovery\x12=\n\x12RequestMissingLogs\x12\x15.unary.missing_number\x1a\x0c.unary.ping2\"\x00(\x01\x12*\n\nBackOnline\x12\x0c.unary.ping2\x1a\x0c.unary.ping2\"\x00\x62\x06proto3')



_MISSING_NUMBER = DESCRIPTOR.message_types_by_name['missing_number']
_PING2 = DESCRIPTOR.message_types_by_name['ping2']
missing_number = _reflection.GeneratedProtocolMessageType('missing_number', (_message.Message,), {
  'DESCRIPTOR' : _MISSING_NUMBER,
  '__module__' : 'order2_pb2'
  # @@protoc_insertion_point(class_scope:unary.missing_number)
  })
_sym_db.RegisterMessage(missing_number)

ping2 = _reflection.GeneratedProtocolMessageType('ping2', (_message.Message,), {
  'DESCRIPTOR' : _PING2,
  '__module__' : 'order2_pb2'
  # @@protoc_insertion_point(class_scope:unary.ping2)
  })
_sym_db.RegisterMessage(ping2)

_RECOVERY = DESCRIPTOR.services_by_name['Recovery']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MISSING_NUMBER._serialized_start=23
  _MISSING_NUMBER._serialized_end=83
  _PING2._serialized_start=85
  _PING2._serialized_end=113
  _RECOVERY._serialized_start=115
  _RECOVERY._serialized_end=232
# @@protoc_insertion_point(module_scope)
