# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: front_end.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x66ront_end.proto\x12\x05unary\"%\n\rproduct_front\x12\x14\n\x0cproduct_name\x18\x01 \x01(\t\")\n\x15invalidation_response\x12\x10\n\x08response\x18\x01 \x01(\x05\x32K\n\x05\x46ront\x12\x42\n\nInvalidate\x12\x14.unary.product_front\x1a\x1c.unary.invalidation_response\"\x00\x62\x06proto3')



_PRODUCT_FRONT = DESCRIPTOR.message_types_by_name['product_front']
_INVALIDATION_RESPONSE = DESCRIPTOR.message_types_by_name['invalidation_response']
product_front = _reflection.GeneratedProtocolMessageType('product_front', (_message.Message,), {
  'DESCRIPTOR' : _PRODUCT_FRONT,
  '__module__' : 'front_end_pb2'
  # @@protoc_insertion_point(class_scope:unary.product_front)
  })
_sym_db.RegisterMessage(product_front)

invalidation_response = _reflection.GeneratedProtocolMessageType('invalidation_response', (_message.Message,), {
  'DESCRIPTOR' : _INVALIDATION_RESPONSE,
  '__module__' : 'front_end_pb2'
  # @@protoc_insertion_point(class_scope:unary.invalidation_response)
  })
_sym_db.RegisterMessage(invalidation_response)

_FRONT = DESCRIPTOR.services_by_name['Front']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PRODUCT_FRONT._serialized_start=26
  _PRODUCT_FRONT._serialized_end=63
  _INVALIDATION_RESPONSE._serialized_start=65
  _INVALIDATION_RESPONSE._serialized_end=106
  _FRONT._serialized_start=108
  _FRONT._serialized_end=183
# @@protoc_insertion_point(module_scope)
